apiVersion: v2
name: nginx
version: 0.1.0
nginx:
  image:
    repository: nginx
    tag: latest
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    host: argocd.miniminipenguenler.com

